version: "3.7"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - 'db_volume:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password@123
      - POSTGRES_DB=test_db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d test_db']
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_volume: